# Generated by Django 3.2.4 on 2021-06-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0002_alter_photo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
