# Generated by Django 3.2.4 on 2021-06-15 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0003_alter_photo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_category', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='select',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albumapp.category'),
        ),
    ]
