# Generated by Django 3.2.4 on 2021-06-15 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0004_auto_20210615_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='select',
            new_name='select_category',
        ),
    ]
