# Generated by Django 3.2.4 on 2021-06-15 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0007_rename_photo_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(default='select', null=True, on_delete=django.db.models.deletion.CASCADE, to='albumapp.category'),
        ),
    ]
